/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/2233': RouteRecordInfo<'/posts/2233', '/posts/2233', Record<never, never>, Record<never, never>>,
    '/posts/anmime/1': RouteRecordInfo<'/posts/anmime/1', '/posts/anmime/1', Record<never, never>, Record<never, never>>,
    '/posts/Develop/D1': RouteRecordInfo<'/posts/Develop/D1', '/posts/Develop/D1', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/N1/n1': RouteRecordInfo<'/posts/N1/n1', '/posts/N1/n1', Record<never, never>, Record<never, never>>,
    '/posts/novel/N1': RouteRecordInfo<'/posts/novel/N1', '/posts/novel/N1', Record<never, never>, Record<never, never>>,
    '/posts/study/S1': RouteRecordInfo<'/posts/study/S1', '/posts/study/S1', Record<never, never>, Record<never, never>>,
    '/posts/study/S2': RouteRecordInfo<'/posts/study/S2', '/posts/study/S2', Record<never, never>, Record<never, never>>,
    '/posts/study/S3': RouteRecordInfo<'/posts/study/S3', '/posts/study/S3', Record<never, never>, Record<never, never>>,
    '/posts/study/S4': RouteRecordInfo<'/posts/study/S4', '/posts/study/S4', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
